# Generated by Django 5.1.5 on 2025-01-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
      migrations.CreateModel(
          name='Course',
          fields=[
              ('id', models.BigAutoField(auto_created=True,
               primary_key=True, serialize=False, verbose_name='ID')),
              ('course_name', models.CharField(max_length=200)),
              ('description', models.TextField()),
          ],
      ),
      migrations.CreateModel(
          name='Tag',
          fields=[
              ('id', models.BigAutoField(auto_created=True,
               primary_key=True, serialize=False, verbose_name='ID')),
              ('tag_name', models.CharField(max_length=30)),
          ],
      ),
      migrations.CreateModel(
          name='CourseDateTime',
          fields=[
              ('id', models.BigAutoField(auto_created=True,
               primary_key=True, serialize=False, verbose_name='ID')),
              ('start_time', models.DateTimeField()),
              ('end_time', models.DateTimeField()),
              ('event', models.ForeignKey(
                  on_delete=django.db.models.deletion.CASCADE, to='coursesapi.course')),
          ],
      ),
      migrations.CreateModel(
          name='Picture',
          fields=[
              ('id', models.BigAutoField(auto_created=True,
               primary_key=True, serialize=False, verbose_name='ID')),
              ('picture', models.ImageField(blank=True,
               null=True, upload_to='course_pictures/')),
              ('course', models.ForeignKey(
                  on_delete=django.db.models.deletion.CASCADE, to='coursesapi.course')),
          ],
      ),
      migrations.AddField(
          model_name='course',
          name='tags',
          field=models.ManyToManyField(to='coursesapi.tag'),
      ),
  ]
