# Generated by Django 5.1.5 on 2025-01-19 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('coursesapi', '0001_initial'),
  ]

  operations = [
      migrations.AddField(
          model_name='course',
          name='active',
          field=models.BooleanField(default=True),
      ),
      migrations.AddField(
          model_name='course',
          name='application_deadline',
          field=models.DateTimeField(default=django.utils.timezone.now),
          preserve_default=False,
      ),
      migrations.AddField(
          model_name='course',
          name='cost',
          field=models.FloatField(default=0),
          preserve_default=False,
      ),
      migrations.AddField(
          model_name='course',
          name='course_location',
          field=models.TextField(default='Somewhere'),
          preserve_default=False,
      ),
      migrations.AddField(
          model_name='course',
          name='curr_students',
          field=models.IntegerField(default=0),
      ),
      migrations.AddField(
          model_name='course',
          name='max_students',
          field=models.IntegerField(default=0),
          preserve_default=False,
      ),
  ]
