# Generated by Django 5.1.5 on 2025-01-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('coursesapi', '0002_course_active_course_application_deadline_and_more'),
  ]

  operations = [
      migrations.AlterField(
          model_name='course',
          name='course_location',
          field=models.CharField(max_length=200),
      ),
  ]
