# Generated by Django 5.1.5 on 2025-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0004_alter_coursedatetime_event_alter_picture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='short description here', max_length=200),
            preserve_default=False,
        ),
    ]
