# Generated by Django 5.1.5 on 2025-01-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0005_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='application_page',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
